services:
  api:
    build:
      context: .
    container_name: agent_ticket_api
    working_dir: /app
    command: uvicorn Api.main:app --host 0.0.0.0 --port 8000 --reload
    environment:
      PYTHONPATH: /app
    volumes:
      - .:/app
    ports:
      - "${API_PORT:-8000}:8000"



# Iniciar API:
# docker compose -f ambiente.yaml up --build
#
# Se a porta 8000 estiver ocupada:
# API_PORT=8001 docker compose -f ambiente.yaml up --build

# Conectar no container:
# docker exec -it agent_ticket_api bash

# Desligar ambiente:
# docker compose -f ambiente.yaml down

# criar estrutura de pastas:
#projeto_ia_teste/
#├── models.py
#├── requirements.txt
#├── Schemas/
#│   └── prompt_agente.yaml
#├── Database/
#│   ├── structure.py
#│   └── utils.py
#└── Workers/
#    └── main.py

# adicionar dentro de requirements:
# pyyaml
# pydantic
# python-dotenv

# instalar o requirements.txt
# pip install -r requirements.txt


# passar arquivo yaml para dentro da pasta do projeto para criar um ambiente Docker
# executa Docker composse up -f ambiente.yaml
# executa ./comando_conectar_ambiente.sh ( que executa o arquivo que tem dentro da pasta que conecta ao ambiente )
